name: Deploy FastAPI with Docker Compose

on:
  push:
    branches:
      - jwt-rbac-auth  # your branch name

env:
  EC2_HOST: 13.239.240.4
  EC2_USER: ec2-user

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up SSH key
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.EC2_SSH_KEY }}" > ~/.ssh/id_rsa
          chmod 600 ~/.ssh/id_rsa

      - name: Add EC2 host to known hosts
        run: |
          ssh-keyscan -H ${{ env.EC2_HOST }} >> ~/.ssh/known_hosts

      - name: Deploy to EC2
        run: |
          ssh -o StrictHostKeyChecking=no -i ~/.ssh/id_rsa ${{ env.EC2_USER }}@${{ env.EC2_HOST }} << 'EOF'
            cd /home/ec2-user/api_2  # update this path if needed
            git pull origin jwt-rbac-auth
            docker-compose down
            docker-compose up -d --build
          EOF

